version: '3'
services:

  cloud-game:
    build: .
    image: cloud-game-local
    container_name: cloud-game-local
    privileged: true
    environment:
      - DISPLAY=:99
      - MESA_GL_VERSION_OVERRIDE=3.3
    # network_mode: "host"
    command: >
      bash -c "Xvfb :99 & coordinator --v=5 & worker --coordinatorhost 192.168.0.10:8001"
    ports:
      - "8001:8001"
      - "9001:9001"
    volumes:
      # keep cores persistent in the cloud-game_cores volume
      - cores:/usr/local/share/cloud-game/assets/cores
      - ${CLOUD_GAME_GAMES_PATH}:/usr/local/share/cloud-game/assets/games

volumes:
  cores:
